### 1. PyTorch Basic Tensor Operation

This example shows how to create tensors, perform basic operations, and move tensors between CPU and GPU

In [2]:
import torch

# Creating a tensor
tensor = torch.tensor([[1, 2], [3, 4]], dtype = torch.float32)
print("Tensor:\n", tensor)

Tensor:
 tensor([[1., 2.],
        [3., 4.]])


In [3]:
# Basic operations
tensor_sum = tensor + tensor
tensor_product = tensor * tensor

print("\nSum of tensors:\n", tensor_sum)
print("\nElement-wise product of tensors:\n", tensor_product)


Sum of tensors:
 tensor([[2., 4.],
        [6., 8.]])

Element-wise product of tensors:
 tensor([[ 1.,  4.],
        [ 9., 16.]])


In [4]:
#check for GPU and move tensor to GPU if available
if torch.cuda.is_available():
    tensor_gpu = tensor.to('cuda')
    print("\nTensor moved to GPU:\n", tensor_gpu)
else:
    print("\nCUDA not available.")


CUDA not available.
