### 1. PyTorch Basic Tensor Operation

This example shows how to create tensors, perform basic operations, and move tensors between CPU and GPU. </br>
-https://medium.com/red-buffer/training-an-object-detection-model-in-a-few-minutes-using-detectron2-5bd0aa5550d4

In [1]:
import torch

# Creating a tensor
tensor = torch.tensor([[1, 2], [3, 4]], dtype = torch.float32)
print("Tensor:\n", tensor)

Tensor:
 tensor([[1., 2.],
        [3., 4.]])


In [2]:
# Basic operations
tensor_sum = tensor + tensor
tensor_product = tensor * tensor

print("\nSum of tensors:\n", tensor_sum)
print("\nElement-wise product of tensors:\n", tensor_product)


Sum of tensors:
 tensor([[2., 4.],
        [6., 8.]])

Element-wise product of tensors:
 tensor([[ 1.,  4.],
        [ 9., 16.]])


In [3]:
#check for GPU and move tensor to GPU if available
if torch.cuda.is_available():
    tensor_gpu = tensor.to('cuda')
    print("\nTensor moved to GPU:\n", tensor_gpu)
else:
    print("\nCUDA not available.")


Tensor moved to GPU:
 tensor([[1., 2.],
        [3., 4.]], device='cuda:0')


### 2. Simple Linear Model

This example demonstrates how to define a simple linear regression model using PyTorch and perform a forward pass

In [4]:
import torch
import torch.nn as nn

#Simple linear model
class LinearModel(nn.Module):
    def __init__(self):
        super(LinearModel, self).__init__()
        self.linear = nn.Linear(1, 1) # 1 input, 1 output

    def forward(self, x):
        return self.linear(x)

#create model and input
model = LinearModel()
x =  torch.tensor([[5.0]]) #Input tensor

#Forward pass
output = model(x)
print("Model output:", output)

Model output: tensor([[-1.8639]], grad_fn=<AddmmBackward0>)


## 3. Autograd and Backpropagation

This example shows how PyTorch's automatic differentiation engine (autograd) works by computing gradients.

In [6]:
# Create tensor with requires_grad=True to track computations
x = torch.tensor(2.0, requires_grad = True)

# Perform operations
y = x ** 2 + 3 * x + 1

# Backpropagate to compute gradients
y.backward()

#Gradient of y with respect to x
print("Gradient of y with respect to x:", x.grad)

Gradient of y with respect to x: tensor(7.)


## 4. Fine-Tuning a CNN (Last Layer)

In this example, We'll load a pre-trained ResNet model, freeze its layers, and fine-tune the last fully connected layer for a new classification task (e.g., from 1000 classes to 10)

In [7]:
import torch
import torch.nn as nn
import torchvision.models as models

# Load pre-trained ResNet
model = models.resnet18(pretrained = True)

# Freeze all layers except the last fully connected layer
for param in model.parameters():
    param.requires_grad = False

#Modify the last fully connected layer to output 10 classes instead of 1000
model.fc = nn.Linear(model.fc.in_features, 10)

# Example input tensor (batch size 1, 3 channels, 224*224)
input_tensor = torch.randn(1, 3, 224, 224)

#Forward pass
output = model(input_tensor)

print("output shape:", output.shape)

C:\Users\kandu\anaconda3\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\kandu\anaconda3\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\kandu/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100%|█████████████████████████████████████████████████████████████████████████████| 44.7M/44.7M [00:05<00:00, 8.59MB/s]


output shape: torch.Size([1, 10])
